### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by JackHaxSmith** [AnezkaGilderWood/Team-B#34]
https://www.jetbrains.com/help/pycharm/refactoring-convert.html

this might be useful to look at on packaging the code. I'll look into it more and mention anything useful here

**Comment by JackHaxSmith** [comment]
https://packaging.python.org/en/latest/tutorials/packaging-projects/

This website seems better. I'm going do some reading into it and generalise it here in this conversation.

**Comment by JackHaxSmith** [comment]
Looks like this is run through the powershell and might require an updated version of pip

Where they have "example.py", that should be the name of our code

The website gives the code (and tells us to copy their code) needed to make this work, once the codes have been finished off and ready to put in one file, sorting out this library thing will be possible

**Comment by JamesGathercole** [comment]
Looks like an excellent plan nice bit of research!

**Comment by JackHaxSmith** [comment]
Could other people have a look through at this please, it's not fully making sense to me
