### ISSUE TITLE
double derivative of x

### ISSUE THREAD

**Issue by Anusheh02** [AnezkaGilderWood/Team-B#7]
either write as a derivative of x func to be applied twice or loop it to do a double derivative within one func

**Comment by AnezkaGilderWood** [comment]
work amended see commit e0b0c04

**Comment by Anusheh02** [comment]
just looking through the code we need to look at the else statement at the end of form as we have another input but no path as to what happens after alternatively we could put an end into the else as the input is invalid this would end the while loop before the return

**Comment by Anusheh02** [comment]
for now i think we should remove the form def and trouble shoot the derivative def

**Comment by AnezkaGilderWood** [comment]
good idea

**Comment by Anusheh02** [comment]
we can take out the v_x variable as this isn't dependent on the differential

**Comment by Anusheh02** [comment]
hey i wrote a time derivative function for 1st order i think this can be edited and used here 
i also like the pre saved function input types you had and i think we should keep that on yours and add it to mine that way it will reduce user input errors
