### ISSUE TITLE
calling values for a wavefunction

### ISSUE THREAD

**Issue by AnezkaGilderWood** [AnezkaGilderWood/Team-B#9]

**Comment by AnezkaGilderWood** [comment]
work amended see commit e0b0c04

**Comment by Anusheh02** [comment]
hey im trying to think of some pre set function options to add to help reduce user error got any eq suggestions

**Comment by AnezkaGilderWood** [comment]
other than polynomials and sine and cosine graphs, how about exponential or non-linear equations?

**Comment by Anusheh02** [comment]
awesome so far we have
ax**b
acos(x) + ibsin(x)
ax**2 + bx + c
ax + b

**Comment by AnezkaGilderWood** [comment]
Thats great

**Comment by Anusheh02** [comment]
im just writing the input options would you be ok to write the if statements for the inputs 1-5 after i send across what ive done

**Comment by AnezkaGilderWood** [comment]
That's fine with me, if you push up I'll get your work and continue.

**Comment by Anusheh02** [comment]
While you do that ill write the doc

**Comment by Anusheh02** [comment]
doc string is done plus i patched a small syntax error

**Comment by AnezkaGilderWood** [comment]
okay adding the equations now, how to i write i in python?

**Comment by Anusheh02** [comment]
j is used in python 
but to be safe we can always put in a j = np.sqrt(-1)

**Comment by AnezkaGilderWood** [comment]
I've uploaded can you run a test on it please?

**Comment by Anusheh02** [comment]
run the tests we need to loop this through x values in an array but this can be done outside our definition
